### ISSUE TITLE
go: gopkg.in/jcmturner/rpc.v1@v1.1.1: go.mod has non-....v1 module path "github.com/jcmturner/rpc" at revision v1.1.1

### ISSUE THREAD

**Issue by hyacinthus** [jcmturner/rpc#1]
go: gopkg.in/jcmturner/rpc.v1@v1.1.1: go.mod has non-....v1 module path "github.com/jcmturner/rpc" at revision v1.1.1

This package is dep of cloud.google.com/go@v0.41.0 

and now all my project can't run "go get -u".

**Comment by jcmturner** [comment]
I have changed the release that caused this issue to be a major version change. I have been moving a number of projects to be go modules and removing the need for gopkg.in and .v1 names. Does this fix things for you? You can update imports to github.com/jcmturner/rpc when you are ready.

Sorry for the inconvenience.

**Comment by hyacinthus** [comment]
Thank you. It works.
