### ISSUE TITLE
gopkg.in/jcmturner/rpc.v1@v1.1.1: parsing go.mod: missing module line. I met this.

### ISSUE THREAD

**Issue by hetiansu5** [jcmturner/rpc#2]
When I do 'go get -u github.com/qit-team/snow/tool/snow', it worked  some days ago. But now it donot woked.

**Comment by zhaiyjgithub** [comment]
same error.

**Comment by zhaiyjgithub** [comment]
try: go get  github.com/qit-team/snow/tool/snow @hetiansu5

**Comment by One2r** [comment]
same error.

**Comment by aofei** [comment]
Are you guys using [proxy.golang.org](https://proxy.golang.org)? If so, please see this: https://github.com/golang/go/issues/34033.

**Comment by jcmturner** [comment]
Hi all, is this still an issue?

**Comment by aofei** [comment]
@jcmturner Fixed https://github.com/golang/go/issues/34033#issuecomment-527505140. This issue can now be closed.

**Comment by jcmturner** [comment]
Thanks!
