### ISSUE TITLE
Reducing memory footprint by replacing fmt.Sprintf()

### ISSUE THREAD

**Issue by L11R** [jcmturner/rpc#3]
Hi, can we replace fmt.Sprintf across this library? I use gokrb5 library and it eats tons of memory just by using it:

![изображение](https://user-images.githubusercontent.com/5345489/98934449-26b54980-24f3-11eb-89ea-e4cbdbd548db.png)

**Comment by jcmturner** [comment]
H, thanks for pointing this out. I'm made some changes to use strings.Builder that should improve this. I'll look to get gokrb5 updated to use this version.

**Comment by savely-krasovsky** [comment]
@jcmturner thanks for so fast fix 👍
